21 de noviembre de 2023, 11:01:37 p. m. COT[DispatchThread: [com.ibm.mq.jmqi.remote.impl.RemoteSession[:/60b8e514][connectionId=414D5143514D31202020202020202020A1795D65004A0040,traceIdentifier=1,remoteTraceIdentifier=-1]]] com.ibm.msg.client.jakarta.jms.internal.JmsProviderExceptionListener
Se ha enviado una excepción al escucha de excepciones de la conexión: '
                       Mensaje : com.ibm.msg.client.jakarta.jms.DetailedJMSException: JMSWMQ1107: Ha surgido un problema con esta conexión.
Se ha producido un error con la conexión JMS de IBM MQ.
Utilice la excepción enlazada para determinar la causa de este error.
                         Clase : class com.ibm.msg.client.jakarta.jms.DetailedJMSException
                          Pila : com.ibm.msg.client.jakarta.wmq.common.internal.Reason.reasonToException(Reason.java:595)
                               : com.ibm.msg.client.jakarta.wmq.common.internal.Reason.createException(Reason.java:215)
                               : com.ibm.msg.client.jakarta.wmq.internal.WMQConnection.consumer(WMQConnection.java:939)
                               : com.ibm.mq.jmqi.remote.api.RemoteHconn.callEventHandler(RemoteHconn.java:3046)
                               : com.ibm.mq.jmqi.remote.api.RemoteHconn.driveEventsEH(RemoteHconn.java:723)
                               : com.ibm.mq.jmqi.remote.impl.RemoteDispatchThread.processHconn(RemoteDispatchThread.java:684)
                               : com.ibm.mq.jmqi.remote.impl.RemoteDispatchThread.run(RemoteDispatchThread.java:223)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
                               : com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
                               : com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1240)
     Se debe a [1] --> Mensaje : com.ibm.mq.MQException: JMSCMQ0001: La llamada de IBM MQ ha fallado con código de terminación '2' ('MQCC_FAILED') razón '2009' ('MQRC_CONNECTION_BROKEN').
                         Clase : class com.ibm.mq.MQException
                          Pila : com.ibm.msg.client.jakarta.wmq.common.internal.Reason.createException(Reason.java:203)
                               : com.ibm.msg.client.jakarta.wmq.internal.WMQConnection.consumer(WMQConnection.java:939)
                               : com.ibm.mq.jmqi.remote.api.RemoteHconn.callEventHandler(RemoteHconn.java:3046)
                               : com.ibm.mq.jmqi.remote.api.RemoteHconn.driveEventsEH(RemoteHconn.java:723)
                               : com.ibm.mq.jmqi.remote.impl.RemoteDispatchThread.processHconn(RemoteDispatchThread.java:684)
                               : com.ibm.mq.jmqi.remote.impl.RemoteDispatchThread.run(RemoteDispatchThread.java:223)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
                               : com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
                               : com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1240)
'.

EXPLICACIÓN:
null

ACCIÓN:
Revise los detalles de la excepción para obtener más información.
--------------------------------------------------------------------
21 de noviembre de 2023, 11:09:07 p. m. COT[DispatchThread: [com.ibm.mq.jmqi.remote.impl.RemoteSession[:/59b644be][connectionId=414D5143514D31202020202020202020AF7D5D65002C0040,traceIdentifier=1,remoteTraceIdentifier=-1]]] com.ibm.msg.client.jakarta.jms.internal.JmsProviderExceptionListener
Se ha enviado una excepción al escucha de excepciones de la conexión: '
                       Mensaje : com.ibm.msg.client.jakarta.jms.DetailedJMSException: JMSWMQ1107: Ha surgido un problema con esta conexión.
Se ha producido un error con la conexión JMS de IBM MQ.
Utilice la excepción enlazada para determinar la causa de este error.
                         Clase : class com.ibm.msg.client.jakarta.jms.DetailedJMSException
                          Pila : com.ibm.msg.client.jakarta.wmq.common.internal.Reason.reasonToException(Reason.java:595)
                               : com.ibm.msg.client.jakarta.wmq.common.internal.Reason.createException(Reason.java:215)
                               : com.ibm.msg.client.jakarta.wmq.internal.WMQConnection.consumer(WMQConnection.java:939)
                               : com.ibm.mq.jmqi.remote.api.RemoteHconn.callEventHandler(RemoteHconn.java:3046)
                               : com.ibm.mq.jmqi.remote.api.RemoteHconn.driveEventsEH(RemoteHconn.java:723)
                               : com.ibm.mq.jmqi.remote.impl.RemoteDispatchThread.processHconn(RemoteDispatchThread.java:684)
                               : com.ibm.mq.jmqi.remote.impl.RemoteDispatchThread.run(RemoteDispatchThread.java:223)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
                               : com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
                               : com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1240)
     Se debe a [1] --> Mensaje : com.ibm.mq.MQException: JMSCMQ0001: La llamada de IBM MQ ha fallado con código de terminación '2' ('MQCC_FAILED') razón '2009' ('MQRC_CONNECTION_BROKEN').
                         Clase : class com.ibm.mq.MQException
                          Pila : com.ibm.msg.client.jakarta.wmq.common.internal.Reason.createException(Reason.java:203)
                               : com.ibm.msg.client.jakarta.wmq.internal.WMQConnection.consumer(WMQConnection.java:939)
                               : com.ibm.mq.jmqi.remote.api.RemoteHconn.callEventHandler(RemoteHconn.java:3046)
                               : com.ibm.mq.jmqi.remote.api.RemoteHconn.driveEventsEH(RemoteHconn.java:723)
                               : com.ibm.mq.jmqi.remote.impl.RemoteDispatchThread.processHconn(RemoteDispatchThread.java:684)
                               : com.ibm.mq.jmqi.remote.impl.RemoteDispatchThread.run(RemoteDispatchThread.java:223)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.runTask(WorkQueueItem.java:319)
                               : com.ibm.msg.client.commonservices.workqueue.SimpleWorkQueueItem.runItem(SimpleWorkQueueItem.java:99)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueItem.run(WorkQueueItem.java:343)
                               : com.ibm.msg.client.commonservices.workqueue.WorkQueueManager.runWorkQueueItem(WorkQueueManager.java:312)
                               : com.ibm.msg.client.commonservices.j2se.workqueue.WorkQueueManagerImplementation$ThreadPoolWorker.run(WorkQueueManagerImplementation.java:1240)
'.

EXPLICACIÓN:
null

ACCIÓN:
Revise los detalles de la excepción para obtener más información.
--------------------------------------------------------------------
21 de noviembre de 2023, 11:53:40 p. m. COT[RMI TCP Connection(2)-172.19.32.1] com.ibm.mq.ese.intercept.JmqiConnInterceptorImpl
Error interno de IBM MQ Advanced Message Security: no se han podido consultar las propiedades del gestor de colas ('2035').
El interceptor de IBM MQ Advanced Message Security no ha podido consultar las propiedades del gestor de colas porque se ha producido un error interno.
Asegúrese de que el gestor de colas está conectado a través de IBM MQ Advanced Message Security. Si el problema persiste, póngase en contacto con el representante de servicio de IBM.
--------------------------------------------------------------------
21 de noviembre de 2023, 11:55:55 p. m. COT[RMI TCP Connection(1)-172.19.32.1] com.ibm.mq.ese.intercept.JmqiConnInterceptorImpl
Error interno de IBM MQ Advanced Message Security: no se han podido consultar las propiedades del gestor de colas ('2035').
El interceptor de IBM MQ Advanced Message Security no ha podido consultar las propiedades del gestor de colas porque se ha producido un error interno.
Asegúrese de que el gestor de colas está conectado a través de IBM MQ Advanced Message Security. Si el problema persiste, póngase en contacto con el representante de servicio de IBM.
--------------------------------------------------------------------
22 de noviembre de 2023, 12:02:59 a. m. COT[RMI TCP Connection(2)-172.19.32.1] com.ibm.mq.ese.intercept.JmqiConnInterceptorImpl
Error interno de IBM MQ Advanced Message Security: no se han podido consultar las propiedades del gestor de colas ('2035').
El interceptor de IBM MQ Advanced Message Security no ha podido consultar las propiedades del gestor de colas porque se ha producido un error interno.
Asegúrese de que el gestor de colas está conectado a través de IBM MQ Advanced Message Security. Si el problema persiste, póngase en contacto con el representante de servicio de IBM.
--------------------------------------------------------------------
22 de noviembre de 2023, 12:19:37 a. m. COT[RMI TCP Connection(1)-172.19.32.1] com.ibm.mq.ese.intercept.JmqiConnInterceptorImpl
Error interno de IBM MQ Advanced Message Security: no se han podido consultar las propiedades del gestor de colas ('2035').
El interceptor de IBM MQ Advanced Message Security no ha podido consultar las propiedades del gestor de colas porque se ha producido un error interno.
Asegúrese de que el gestor de colas está conectado a través de IBM MQ Advanced Message Security. Si el problema persiste, póngase en contacto con el representante de servicio de IBM.
--------------------------------------------------------------------
